_commit: v1.8.1
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageEnabled: true
ingClass: nginx-internal
ingCname: ''
ingExtraAnnotations: ''
ingHost: prowlarr.crt.house
ingName: prowlarr
ingPathType: Prefix
ingWebSockets: true
ingress: true
labels: ''
name: prowlarr
namespace: prowlarr
pvc: false
reloader: true
resources:
- backups.yaml
- deployments.yaml
- external-secrets.yaml
- ingresses.yaml
- pvcs.yaml
- service-accounts.yaml
- services.yaml
- statefulsets.yaml
service: false
serviceAccount: false
svcName: prowlarr
svcPortNum: 9696
upstreamURL: https://prowlarr.com/
url: https://github.com/charlesthomas/homelab-prowlarr
