_commit: v1.12.1-6-gbf0c0a5
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false 
helm: false
homepageDescription: Media Indexer
homepageEnabled: true
homepageGroup: Media
homepageIcon: prowlarr
homepageName: Prowlarr
ingClass: nginx-internal
ingCname: ''
ingExtraAnnotations: ''
ingHost: prowlarr.crt.house
ingName: prowlarr
ingPathType: Prefix
ingWebSockets: true
ingress: true
labels: ''
name: prowlarr
namespace: prowlarr
pvc: false
reloader: true
resources:
- deployments.yaml
- external-secrets.yaml
- ingresses.yaml
- pvcs.yaml
- service-accounts.yaml
- services.yaml
- statefulsets.yaml
service: false
serviceAccount: false
svcName: prowlarr
svcPortNum: 9696
upstreamURL: https://prowlarr.com/
url: https://github.com/charlesthomas/homelab-prowlarr
